### PR TITLE
fix: undefined event

### PR DESCRIPTION
**Pull request by ofekashery**

### CODE REVIEW

**Comment by jvens** [comment]
If this was suppose to fix the undefined event issue it doesn't.  I am still seeing the issue with this patch.

Steps to reproduce:
1. clear cached data or otherwise start with a clean version of DS tool
2. select scorekeeper IP, event, and log into TOA
3. do not select event and close out of the DS tool
4. restart DS tool.  You will now see that event is set to `undefined`

**Comment by ofekashery** [comment]
@jvens oh, I understood your problem differently.
I tried your reproduce steps, it opens the select event page as it should be.
https://github.com/orange-alliance/TOA-DataSync/blob/e1bd573ee0cdd4b9a95f9ee9b68166512a0ed38c/src/index.html#L37-L41

**Comment by jvens** [comment]
Here is a video of me reproducing the issue: https://youtu.be/lDqT1TctTg8

Not the only different between what I am running and the github master right now is I added `win.webContents.openDevTools();` at `main.js:30`

**Comment by ofekashery** [comment]
Interesting..
Can I have your logs? Right click > save logs

**Comment by jvens** [comment]
`Right click > save logs` is causing electron to completely crash without any errors.  I'm assuming that is not the intended result from that action.  I'll dig into that a little bit and see if I can send you log files soon, and hopefully know what it crashes when I try.

I doubt this maters, but I am running this on Ubuntu 19.04 and using Node 10.15.2.

**Comment by ofekashery** [comment]
Okay, let's try to get the localStorage.
```js
JSON.stringify(localStorage['CONFIG-EVENTS'])
```

**Comment by jvens** [comment]
Before closing out the first time:

```
JSON.stringify(localStorage['CONFIG-EVENTS'])
""[{\"event_id\":\"vt_refs\",\"name\":\"Volunteer Training Refs\"}]""
```

After closing and relaunching:

```
JSON.stringify(localStorage['CONFIG-EVENTS'])
""[{\"event_id\":\"vt_refs\",\"name\":\"Volunteer Training Refs\"}]""
```
I think I see the problem.  The if on line `index.html:38` is going to evaluate true and set `location.href` correctly.  But there is nothing stopping you from the reassigning that value at `index.html:61`.  Just adding a `return` statement at line 40 fixed the problem for me.

I still need to dig into why saving logs crashes electron.

**Comment by ofekashery** [comment]
You're right! Thanks!!

**Pull request merged**
